export type CatalogRow = Readonly<Record<string, string | number>>;

export const POZYTYWKA_SEASON_2026_2027 = {
  SEASON_ID: "2026-2027",
  NAME: "2026/2027",
  START_DATE: "2026-09-01",
  END_DATE: "2027-07-31",
  ACTIVE: "TAK",
  SORT_ORDER: 10,
} as const satisfies CatalogRow;

export const POZYTYWKA_CITIES_2026_2027: readonly CatalogRow[] = [
  { CITY_ID: "olkusz", NAME: "Olkusz · Klub Przyjaźń", ACTIVE: "TAK", SORT_ORDER: 10 },
  { CITY_ID: "bukowno", NAME: "Bukowno · MOK Bukowno", ACTIVE: "TAK", SORT_ORDER: 20 },
  {
    CITY_ID: "boleslaw",
    NAME: "Bolesław · Centrum Kultury",
    ACTIVE: "TAK",
    SORT_ORDER: 30,
  },
];

export const POZYTYWKA_OFFERINGS_2026_2027: readonly CatalogRow[] = [
  {
    OFFERING_ID: "olkusz-psikusy",
    CITY_ID: "olkusz",
    NAME: "Psikusy · 4-6 lat",
    PUBLIC_DESCRIPTION:
      "Zespół wokalno-taneczny. Poniedziałki 16:15-17:15. Opłata 160 zł / miesiąc.",
    ACTIVE: "TAK",
    SORT_ORDER: 10,
    REGISTRATION_MODE: "ROLLING",
    INTAKE_STATE: "OPEN",
    REGISTRATION_OPEN_FROM: "",
    REGISTRATION_OPEN_TO: "",
    WAITLIST_ENABLED: "TRUE",
  },
  {
    OFFERING_ID: "olkusz-psotki",
    CITY_ID: "olkusz",
    NAME: "Psotki · 7+",
    PUBLIC_DESCRIPTION:
      "Zespół wokalno-taneczny dla dzieci. Wtorki 16:15-18:15. Opłata 230 zł / miesiąc.",
    ACTIVE: "TAK",
    SORT_ORDER: 20,
    REGISTRATION_MODE: "ROLLING",
    INTAKE_STATE: "OPEN",
    REGISTRATION_OPEN_FROM: "",
    REGISTRATION_OPEN_TO: "",
    WAITLIST_ENABLED: "TRUE",
  },
  {
    OFFERING_ID: "olkusz-balet-piruet",
    CITY_ID: "olkusz",
    NAME: "Szkółka Baletu Pozytywka · Piruet · 4+",
    PUBLIC_DESCRIPTION: "Poniedziałki 17:15-18:15. Opłata 160 zł / miesiąc.",
    ACTIVE: "TAK",
    SORT_ORDER: 30,
    REGISTRATION_MODE: "ROLLING",
    INTAKE_STATE: "OPEN",
    REGISTRATION_OPEN_FROM: "",
    REGISTRATION_OPEN_TO: "",
    WAITLIST_ENABLED: "TRUE",
  },
  {
    OFFERING_ID: "olkusz-zespol-wokalny",
    CITY_ID: "olkusz",
    NAME: "Zespół wokalny · 10+",
    PUBLIC_DESCRIPTION: "Zajęcia dla dzieci 10+. Poniedziałki od 18:30. Opłata 160 zł / miesiąc.",
    ACTIVE: "TAK",
    SORT_ORDER: 40,
    REGISTRATION_MODE: "ROLLING",
    INTAKE_STATE: "OPEN",
    REGISTRATION_OPEN_FROM: "",
    REGISTRATION_OPEN_TO: "",
    WAITLIST_ENABLED: "TRUE",
  },
  {
    OFFERING_ID: "olkusz-stepdance",
    CITY_ID: "olkusz",
    NAME: "StepDance · dorośli",
    PUBLIC_DESCRIPTION: "Zajęcia inspirowane tańcem i fitnessem. Poniedziałki od 18:15.",
    ACTIVE: "TAK",
    SORT_ORDER: 50,
    REGISTRATION_MODE: "ROLLING",
    INTAKE_STATE: "OPEN",
    REGISTRATION_OPEN_FROM: "",
    REGISTRATION_OPEN_TO: "",
    WAITLIST_ENABLED: "TRUE",
  },
  {
    OFFERING_ID: "olkusz-acrodance-5-8",
    CITY_ID: "olkusz",
    NAME: "AcroDance · 5-8 lat · początkująca",
    PUBLIC_DESCRIPTION:
      "Grupa taneczno-akrobatyczna początkująca. Wtorki od 16:15. Opłata 180 zł / miesiąc.",
    ACTIVE: "TAK",
    SORT_ORDER: 60,
    REGISTRATION_MODE: "ROLLING",
    INTAKE_STATE: "OPEN",
    REGISTRATION_OPEN_FROM: "",
    REGISTRATION_OPEN_TO: "",
    WAITLIST_ENABLED: "TRUE",
  },
  {
    OFFERING_ID: "olkusz-acrodance-9-plus",
    CITY_ID: "olkusz",
    NAME: "AcroDance · 9+ · zaawansowana",
    PUBLIC_DESCRIPTION:
      "Grupa taneczno-akrobatyczna zaawansowana dla dzieci. Wtorki od 17:15. Opłata 180 zł / miesiąc.",
    ACTIVE: "TAK",
    SORT_ORDER: 70,
    REGISTRATION_MODE: "ROLLING",
    INTAKE_STATE: "OPEN",
    REGISTRATION_OPEN_FROM: "",
    REGISTRATION_OPEN_TO: "",
    WAITLIST_ENABLED: "TRUE",
  },
  {
    OFFERING_ID: "olkusz-teatr-pod-czarnym-kotem",
    CITY_ID: "olkusz",
    NAME: "Teatr pod Czarnym Kotem",
    PUBLIC_DESCRIPTION: "Dziecięcy teatr muzyczny. Wtorki 17:15-19:15. Opłata 240 zł.",
    ACTIVE: "TAK",
    SORT_ORDER: 80,
    REGISTRATION_MODE: "ROLLING",
    INTAKE_STATE: "OPEN",
    REGISTRATION_OPEN_FROM: "",
    REGISTRATION_OPEN_TO: "",
    WAITLIST_ENABLED: "TRUE",
  },
  {
    OFFERING_ID: "olkusz-plasanie",
    CITY_ID: "olkusz",
    NAME: "Pląsanie · do 4 lat z opiekunem",
    PUBLIC_DESCRIPTION:
      "Zajęcia muzyczno-ruchowe dla dzieci z opiekunem. Poniedziałki od 17:30. Opłata 50 zł / zajęcia.",
    ACTIVE: "TAK",
    SORT_ORDER: 90,
    REGISTRATION_MODE: "ROLLING",
    INTAKE_STATE: "OPEN",
    REGISTRATION_OPEN_FROM: "",
    REGISTRATION_OPEN_TO: "",
    WAITLIST_ENABLED: "TRUE",
  },
  {
    OFFERING_ID: "bukowno-psikusy",
    CITY_ID: "bukowno",
    NAME: "Psikusy · 4-6 lat",
    PUBLIC_DESCRIPTION: "Zespół wokalno-taneczny. Czwartki 16:45-17:45. Opłata 160 zł / miesiąc.",
    ACTIVE: "TAK",
    SORT_ORDER: 110,
    REGISTRATION_MODE: "ROLLING",
    INTAKE_STATE: "OPEN",
    REGISTRATION_OPEN_FROM: "",
    REGISTRATION_OPEN_TO: "",
    WAITLIST_ENABLED: "TRUE",
  },
  {
    OFFERING_ID: "bukowno-psotki",
    CITY_ID: "bukowno",
    NAME: "Psotki · 7+",
    PUBLIC_DESCRIPTION:
      "Zespół wokalno-taneczny dla dzieci. Czwartki 15:45-17:45. Opłata 230 zł / miesiąc.",
    ACTIVE: "TAK",
    SORT_ORDER: 120,
    REGISTRATION_MODE: "ROLLING",
    INTAKE_STATE: "OPEN",
    REGISTRATION_OPEN_FROM: "",
    REGISTRATION_OPEN_TO: "",
    WAITLIST_ENABLED: "TRUE",
  },
  {
    OFFERING_ID: "bukowno-inside-5-8",
    CITY_ID: "bukowno",
    NAME: "Inside · 5-8 lat · początkująca",
    PUBLIC_DESCRIPTION:
      "Grupa taneczno-akrobatyczna początkująca. Środy od 15:15. Opłata 160 zł / miesiąc.",
    ACTIVE: "TAK",
    SORT_ORDER: 130,
    REGISTRATION_MODE: "ROLLING",
    INTAKE_STATE: "OPEN",
    REGISTRATION_OPEN_FROM: "",
    REGISTRATION_OPEN_TO: "",
    WAITLIST_ENABLED: "TRUE",
  },
  {
    OFFERING_ID: "bukowno-inside-9-plus",
    CITY_ID: "bukowno",
    NAME: "Inside · 9+ · zaawansowana",
    PUBLIC_DESCRIPTION:
      "Grupa taneczno-akrobatyczna zaawansowana dla dzieci. Czwartki od 17:45. Opłata 160 zł / miesiąc.",
    ACTIVE: "TAK",
    SORT_ORDER: 140,
    REGISTRATION_MODE: "ROLLING",
    INTAKE_STATE: "OPEN",
    REGISTRATION_OPEN_FROM: "",
    REGISTRATION_OPEN_TO: "",
    WAITLIST_ENABLED: "TRUE",
  },
  {
    OFFERING_ID: "bukowno-balet-arabeska",
    CITY_ID: "bukowno",
    NAME: "Szkółka Baletu Pozytywka · Arabeska · 4+",
    PUBLIC_DESCRIPTION: "Czwartki 15:45-16:45. Opłata 160 zł / miesiąc.",
    ACTIVE: "TAK",
    SORT_ORDER: 150,
    REGISTRATION_MODE: "ROLLING",
    INTAKE_STATE: "OPEN",
    REGISTRATION_OPEN_FROM: "",
    REGISTRATION_OPEN_TO: "",
    WAITLIST_ENABLED: "TRUE",
  },
  {
    OFFERING_ID: "bukowno-bez-kurtyny",
    CITY_ID: "bukowno",
    NAME: "Teatr dziecięcy Bez Kurtyny",
    PUBLIC_DESCRIPTION: "Czwartki 17:45-19:15. Opłata 200 zł.",
    ACTIVE: "TAK",
    SORT_ORDER: 160,
    REGISTRATION_MODE: "ROLLING",
    INTAKE_STATE: "OPEN",
    REGISTRATION_OPEN_FROM: "",
    REGISTRATION_OPEN_TO: "",
    WAITLIST_ENABLED: "TRUE",
  },
  {
    OFFERING_ID: "bukowno-synteza-street-dance-squad",
    CITY_ID: "bukowno",
    NAME: "SynTeza · Street Dance Squad · 9-12 lat",
    PUBLIC_DESCRIPTION:
      "Formacja młodzieżowa oparta na stylach ulicznych. Środy 16:15-17:15 i czwartki 18:45-19:45. Opłata 250 zł / miesiąc.",
    ACTIVE: "TAK",
    SORT_ORDER: 170,
    REGISTRATION_MODE: "ROLLING",
    INTAKE_STATE: "OPEN",
    REGISTRATION_OPEN_FROM: "",
    REGISTRATION_OPEN_TO: "",
    WAITLIST_ENABLED: "TRUE",
  },
  {
    OFFERING_ID: "bukowno-babeczki",
    CITY_ID: "bukowno",
    NAME: "Babeczki · dzikie pląsy",
    PUBLIC_DESCRIPTION:
      "Poniedziałki od 18:45. Opłata 50 zł / zajęcia lub karnet miesięczny 160 zł.",
    ACTIVE: "TAK",
    SORT_ORDER: 180,
    REGISTRATION_MODE: "ROLLING",
    INTAKE_STATE: "OPEN",
    REGISTRATION_OPEN_FROM: "",
    REGISTRATION_OPEN_TO: "",
    WAITLIST_ENABLED: "TRUE",
  },
  {
    OFFERING_ID: "boleslaw-synteza-street-dance-kids",
    CITY_ID: "boleslaw",
    NAME: "SynTeza · Street Dance Kids · 6-9 lat",
    PUBLIC_DESCRIPTION:
      "Formacja dziecięca oparta na stylach ulicznych. Środy 18:00-19:00. Opłata 160 zł / miesiąc.",
    ACTIVE: "TAK",
    SORT_ORDER: 210,
    REGISTRATION_MODE: "ROLLING",
    INTAKE_STATE: "OPEN",
    REGISTRATION_OPEN_FROM: "",
    REGISTRATION_OPEN_TO: "",
    WAITLIST_ENABLED: "TRUE",
  },
];

export function pozytywkaGroupsForSeason2026_2027(seasonId: string): readonly CatalogRow[] {
  const olkusz = "Pracownia w Olkuszu przy Klubie Przyjaźń";
  const bukowno = "MOK Bukowno";
  const boleslaw = "Centrum Kultury w Bolesławiu";

  return [
    {
      GROUP_ID: "olkusz-psikusy-2026-2027",
      SEASON_ID: seasonId,
      OFFERING_ID: "olkusz-psikusy",
      NAME: "Psikusy",
      AGE_MIN: 4,
      AGE_MAX: 6,
      DAY_OF_WEEK: "Poniedziałek",
      START_TIME: "16:15",
      END_TIME: "17:15",
      LOCATION: olkusz,
      INSTRUCTOR: "",
      CAPACITY: "",
      ACTIVE: "TAK",
      SORT_ORDER: 10,
    },
    {
      GROUP_ID: "olkusz-psotki-2026-2027",
      SEASON_ID: seasonId,
      OFFERING_ID: "olkusz-psotki",
      NAME: "Psotki",
      AGE_MIN: 7,
      AGE_MAX: 17,
      DAY_OF_WEEK: "Wtorek",
      START_TIME: "16:15",
      END_TIME: "18:15",
      LOCATION: olkusz,
      INSTRUCTOR: "",
      CAPACITY: "",
      ACTIVE: "TAK",
      SORT_ORDER: 20,
    },
    {
      GROUP_ID: "olkusz-balet-piruet-2026-2027",
      SEASON_ID: seasonId,
      OFFERING_ID: "olkusz-balet-piruet",
      NAME: "Piruet",
      AGE_MIN: 4,
      AGE_MAX: 17,
      DAY_OF_WEEK: "Poniedziałek",
      START_TIME: "17:15",
      END_TIME: "18:15",
      LOCATION: olkusz,
      INSTRUCTOR: "",
      CAPACITY: "",
      ACTIVE: "TAK",
      SORT_ORDER: 30,
    },
    {
      GROUP_ID: "olkusz-zespol-wokalny-2026-2027",
      SEASON_ID: seasonId,
      OFFERING_ID: "olkusz-zespol-wokalny",
      NAME: "Zespół wokalny",
      AGE_MIN: 10,
      AGE_MAX: 17,
      DAY_OF_WEEK: "Poniedziałek",
      START_TIME: "18:30",
      END_TIME: "",
      LOCATION: olkusz,
      INSTRUCTOR: "",
      CAPACITY: "",
      ACTIVE: "TAK",
      SORT_ORDER: 40,
    },
    {
      GROUP_ID: "olkusz-stepdance-2026-2027",
      SEASON_ID: seasonId,
      OFFERING_ID: "olkusz-stepdance",
      NAME: "StepDance",
      AGE_MIN: 18,
      AGE_MAX: "",
      DAY_OF_WEEK: "Poniedziałek",
      START_TIME: "18:15",
      END_TIME: "",
      LOCATION: olkusz,
      INSTRUCTOR: "",
      CAPACITY: "",
      ACTIVE: "TAK",
      SORT_ORDER: 50,
    },
    {
      GROUP_ID: "olkusz-acrodance-5-8-2026-2027",
      SEASON_ID: seasonId,
      OFFERING_ID: "olkusz-acrodance-5-8",
      NAME: "AcroDance · grupa początkująca",
      AGE_MIN: 5,
      AGE_MAX: 8,
      DAY_OF_WEEK: "Wtorek",
      START_TIME: "16:15",
      END_TIME: "",
      LOCATION: olkusz,
      INSTRUCTOR: "",
      CAPACITY: "",
      ACTIVE: "TAK",
      SORT_ORDER: 60,
    },
    {
      GROUP_ID: "olkusz-acrodance-9-plus-2026-2027",
      SEASON_ID: seasonId,
      OFFERING_ID: "olkusz-acrodance-9-plus",
      NAME: "AcroDance · grupa zaawansowana",
      AGE_MIN: 9,
      AGE_MAX: 17,
      DAY_OF_WEEK: "Wtorek",
      START_TIME: "17:15",
      END_TIME: "",
      LOCATION: olkusz,
      INSTRUCTOR: "",
      CAPACITY: "",
      ACTIVE: "TAK",
      SORT_ORDER: 70,
    },
    {
      GROUP_ID: "olkusz-teatr-pod-czarnym-kotem-2026-2027",
      SEASON_ID: seasonId,
      OFFERING_ID: "olkusz-teatr-pod-czarnym-kotem",
      NAME: "Teatr pod Czarnym Kotem",
      AGE_MIN: 0,
      AGE_MAX: 17,
      DAY_OF_WEEK: "Wtorek",
      START_TIME: "17:15",
      END_TIME: "19:15",
      LOCATION: olkusz,
      INSTRUCTOR: "",
      CAPACITY: "",
      ACTIVE: "TAK",
      SORT_ORDER: 80,
    },
    {
      GROUP_ID: "olkusz-plasanie-2026-2027",
      SEASON_ID: seasonId,
      OFFERING_ID: "olkusz-plasanie",
      NAME: "Pląsanie",
      AGE_MIN: 0,
      AGE_MAX: 4,
      DAY_OF_WEEK: "Poniedziałek",
      START_TIME: "17:30",
      END_TIME: "",
      LOCATION: olkusz,
      INSTRUCTOR: "",
      CAPACITY: "",
      ACTIVE: "TAK",
      SORT_ORDER: 90,
    },
    {
      GROUP_ID: "bukowno-psikusy-2026-2027",
      SEASON_ID: seasonId,
      OFFERING_ID: "bukowno-psikusy",
      NAME: "Psikusy",
      AGE_MIN: 4,
      AGE_MAX: 6,
      DAY_OF_WEEK: "Czwartek",
      START_TIME: "16:45",
      END_TIME: "17:45",
      LOCATION: bukowno,
      INSTRUCTOR: "",
      CAPACITY: "",
      ACTIVE: "TAK",
      SORT_ORDER: 110,
    },
    {
      GROUP_ID: "bukowno-psotki-2026-2027",
      SEASON_ID: seasonId,
      OFFERING_ID: "bukowno-psotki",
      NAME: "Psotki",
      AGE_MIN: 7,
      AGE_MAX: 17,
      DAY_OF_WEEK: "Czwartek",
      START_TIME: "15:45",
      END_TIME: "17:45",
      LOCATION: bukowno,
      INSTRUCTOR: "",
      CAPACITY: "",
      ACTIVE: "TAK",
      SORT_ORDER: 120,
    },
    {
      GROUP_ID: "bukowno-inside-5-8-2026-2027",
      SEASON_ID: seasonId,
      OFFERING_ID: "bukowno-inside-5-8",
      NAME: "Inside · grupa początkująca",
      AGE_MIN: 5,
      AGE_MAX: 8,
      DAY_OF_WEEK: "Środa",
      START_TIME: "15:15",
      END_TIME: "",
      LOCATION: bukowno,
      INSTRUCTOR: "",
      CAPACITY: "",
      ACTIVE: "TAK",
      SORT_ORDER: 130,
    },
    {
      GROUP_ID: "bukowno-inside-9-plus-2026-2027",
      SEASON_ID: seasonId,
      OFFERING_ID: "bukowno-inside-9-plus",
      NAME: "Inside · grupa zaawansowana",
      AGE_MIN: 9,
      AGE_MAX: 17,
      DAY_OF_WEEK: "Czwartek",
      START_TIME: "17:45",
      END_TIME: "",
      LOCATION: bukowno,
      INSTRUCTOR: "",
      CAPACITY: "",
      ACTIVE: "TAK",
      SORT_ORDER: 140,
    },
    {
      GROUP_ID: "bukowno-balet-arabeska-2026-2027",
      SEASON_ID: seasonId,
      OFFERING_ID: "bukowno-balet-arabeska",
      NAME: "Arabeska",
      AGE_MIN: 4,
      AGE_MAX: 17,
      DAY_OF_WEEK: "Czwartek",
      START_TIME: "15:45",
      END_TIME: "16:45",
      LOCATION: bukowno,
      INSTRUCTOR: "",
      CAPACITY: "",
      ACTIVE: "TAK",
      SORT_ORDER: 150,
    },
    {
      GROUP_ID: "bukowno-bez-kurtyny-2026-2027",
      SEASON_ID: seasonId,
      OFFERING_ID: "bukowno-bez-kurtyny",
      NAME: "Bez Kurtyny",
      AGE_MIN: 0,
      AGE_MAX: 17,
      DAY_OF_WEEK: "Czwartek",
      START_TIME: "17:45",
      END_TIME: "19:15",
      LOCATION: bukowno,
      INSTRUCTOR: "",
      CAPACITY: "",
      ACTIVE: "TAK",
      SORT_ORDER: 160,
    },
    {
      GROUP_ID: "bukowno-synteza-street-dance-squad-2026-2027",
      SEASON_ID: seasonId,
      OFFERING_ID: "bukowno-synteza-street-dance-squad",
      NAME: "SynTeza · Street Dance Squad",
      AGE_MIN: 9,
      AGE_MAX: 12,
      DAY_OF_WEEK: "Śr 16:15-17:15 + czw 18:45-19:45",
      START_TIME: "",
      END_TIME: "",
      LOCATION: bukowno,
      INSTRUCTOR: "",
      CAPACITY: "",
      ACTIVE: "TAK",
      SORT_ORDER: 170,
    },
    {
      GROUP_ID: "bukowno-babeczki-2026-2027",
      SEASON_ID: seasonId,
      OFFERING_ID: "bukowno-babeczki",
      NAME: "Babeczki · dzikie pląsy",
      AGE_MIN: "",
      AGE_MAX: "",
      DAY_OF_WEEK: "Poniedziałek",
      START_TIME: "18:45",
      END_TIME: "",
      LOCATION: bukowno,
      INSTRUCTOR: "",
      CAPACITY: "",
      ACTIVE: "TAK",
      SORT_ORDER: 180,
    },
    {
      GROUP_ID: "boleslaw-synteza-street-dance-kids-2026-2027",
      SEASON_ID: seasonId,
      OFFERING_ID: "boleslaw-synteza-street-dance-kids",
      NAME: "SynTeza · Street Dance Kids",
      AGE_MIN: 6,
      AGE_MAX: 9,
      DAY_OF_WEEK: "Środa",
      START_TIME: "18:00",
      END_TIME: "19:00",
      LOCATION: boleslaw,
      INSTRUCTOR: "",
      CAPACITY: "",
      ACTIVE: "TAK",
      SORT_ORDER: 210,
    },
  ];
}
